# mac2nix: host configuration for __HOSTNAME__
{ config, lib, pkgs, ... }:

{
  # nix-darwin doesn't manage real macOS accounts and has no default for
  # users.users.<name>.home — but home-manager's own darwin integration reads
  # it unconditionally (config.users.users.<name>.home) to derive
  # home.homeDirectory, so leaving it unset makes that derivation null and
  # fails the module system's type check. Set explicitly, not inferred.
  users.users.__USERNAME__.shell = pkgs.zsh;
  users.users.__USERNAME__.home = "/Users/__USERNAME__";

  # Required by nix-darwin — set once per host at onboarding time and never
  # changed afterward (see the assertion message this satisfies).
  system.stateVersion = 7;

  # MAC2NIX:GENERATE:BEGIN -- generated by `mac2nix generate`; do not edit by hand
  # MAC2NIX:GENERATE:END
}
