{
  description = "mac2nix-managed nix-darwin configuration";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    darwin = {
      url = "github:nix-darwin/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    nix-homebrew.url = "github:zhaofengli/nix-homebrew";

    homebrew-core = {
      url = "github:homebrew/homebrew-core";
      flake = false;
    };

    homebrew-cask = {
      url = "github:homebrew/homebrew-cask";
      flake = false;
    };

    mac-app-util.url = "github:hraban/mac-app-util";

    determinate.url = "https://flakehub.com/f/DeterminateSystems/determinate/3";

    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs:
    let
      mkDarwinSystem = import ./lib/helpers.nix { inherit inputs; };
    in
    {
      darwinConfigurations = {
        # MAC2NIX:HOSTS:BEGIN -- generated by `mac2nix add-host`; do not edit by hand
        # MAC2NIX:HOSTS:END
      };
    };
}
