"""Tests for mac2nix.generators.scaffold: init_framework(), add_host(), and ScaffoldError."""

from __future__ import annotations

import contextlib
import json
import logging
import os
import re
import stat
import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest
import yaml

from mac2nix.generators import Mac2NixError
from mac2nix.generators import scaffold as scaffold_module
from mac2nix.generators.scaffold import (
    ScaffoldError,
    add_host,
    age_key_path,
    generate_age_key,
    has_hosts_sentinels,
    init_framework,
)
from tests._scaffold_helpers import _has_add_host_crypto_deps, _has_age_keygen, _redirect_age_keys

_EXPECTED_FRAMEWORK_FILES = [
    ".gitignore",
    "flake.nix",
    "lib/helpers.nix",
    "modules/darwin/default.nix",
    "modules/darwin/homebrew.nix",
    "modules/home-manager/default.nix",
]


def test_scaffold_error_is_mac2nix_error() -> None:
    assert issubclass(ScaffoldError, Mac2NixError)


class TestInitFramework:
    def test_produces_expected_framework_files(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "repo"
        init_framework(output_dir)

        for rel_path in _EXPECTED_FRAMEWORK_FILES:
            assert (output_dir / rel_path).is_file(), f"missing {rel_path}"

    def test_gitignore_renamed_bare_gitignore_absent(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "repo"
        init_framework(output_dir)

        assert (output_dir / ".gitignore").is_file()
        assert not (output_dir / "gitignore").exists()

    def test_flake_nix_has_empty_host_sentinels(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "repo"
        init_framework(output_dir)

        lines = (output_dir / "flake.nix").read_text().splitlines()
        begin_line = next(i for i, line in enumerate(lines) if "MAC2NIX:HOSTS:BEGIN" in line)
        end_line = next(i for i, line in enumerate(lines) if "MAC2NIX:HOSTS:END" in line)

        # The BEGIN marker's own line carries trailing explanatory comment text
        # ("-- generated by ... do not edit by hand") — only lines strictly
        # between the two sentinel lines are the actual host-block content.
        between_lines = lines[begin_line + 1 : end_line]
        assert all(line.strip() == "" for line in between_lines), "sentinel block must be empty right after init"

    def test_produces_no_host_or_secret_state(self, tmp_path: Path) -> None:
        """init_framework() is host-less — hosts/, users/, .sops.yaml, and secrets/
        are add_host()'s responsibility, not init's."""
        output_dir = tmp_path / "repo"
        init_framework(output_dir)

        assert not (output_dir / "hosts").exists()
        assert not (output_dir / "users").exists()
        assert not (output_dir / ".sops.yaml").exists()
        assert not (output_dir / "secrets").exists()

    def test_creates_missing_parent_directories(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "nested" / "repo"
        init_framework(output_dir)
        assert (output_dir / "flake.nix").is_file()

    def test_raises_on_nonempty_directory(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "repo"
        output_dir.mkdir()
        (output_dir / "unrelated.txt").write_text("pre-existing content")

        with pytest.raises(ScaffoldError, match="not empty"):
            init_framework(output_dir)

    def test_raises_on_nonempty_directory_writes_nothing(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "repo"
        output_dir.mkdir()
        (output_dir / "unrelated.txt").write_text("pre-existing content")

        before = sorted(p.relative_to(output_dir) for p in output_dir.rglob("*"))

        with pytest.raises(ScaffoldError):
            init_framework(output_dir)

        after = sorted(p.relative_to(output_dir) for p in output_dir.rglob("*"))
        assert before == after


# ---------------------------------------------------------------------------
# generate_age_key()
# ---------------------------------------------------------------------------


@pytest.fixture
def require_age_keygen() -> None:
    if not _has_age_keygen():
        pytest.skip("age-keygen not on PATH")


@pytest.mark.usefixtures("require_age_keygen")
class TestGenerateAgeKey:
    def test_permissions_and_fingerprint(self, tmp_path: Path) -> None:
        key_dir = tmp_path / "keys"
        fingerprint = generate_age_key("testuser", key_dir=key_dir)

        key_path = key_dir / "keys.txt"
        assert key_path.is_file()
        assert stat.S_IMODE(key_path.stat().st_mode) == 0o600
        assert stat.S_IMODE(key_dir.stat().st_mode) == 0o700

        public_key_line = next(line for line in key_path.read_text().splitlines() if line.startswith("# public key:"))
        assert public_key_line.removeprefix("# public key:").strip() == fingerprint

    def test_second_call_raises_without_modifying_existing_key(self, tmp_path: Path) -> None:
        key_dir = tmp_path / "keys"
        generate_age_key("testuser", key_dir=key_dir)

        key_path = key_dir / "keys.txt"
        before_mtime = key_path.stat().st_mtime_ns
        before_content = key_path.read_text()

        with pytest.raises(ScaffoldError, match="already exists"):
            generate_age_key("testuser", key_dir=key_dir)

        assert key_path.stat().st_mtime_ns == before_mtime
        assert key_path.read_text() == before_content


def test_age_key_path_matches_internal_construction() -> None:
    assert age_key_path("alice") == Path("/Users/alice") / ".config" / "sops" / "age" / "keys.txt"


def test_has_hosts_sentinels_true_when_both_markers_present() -> None:
    assert has_hosts_sentinels("# MAC2NIX:HOSTS:BEGIN\n...\n# MAC2NIX:HOSTS:END\n") is True


def test_has_hosts_sentinels_false_when_a_marker_is_missing() -> None:
    assert has_hosts_sentinels("# MAC2NIX:HOSTS:BEGIN\n...\n") is False
    assert has_hosts_sentinels("not a mac2nix flake at all") is False


# ---------------------------------------------------------------------------
# add_host() — file/directory orchestration and rollback (crypto mocked)
# ---------------------------------------------------------------------------


@contextlib.contextmanager
def _mocked_crypto(*fingerprints: str):
    """Isolate add_host()'s file/directory orchestration from real age-keygen/sops.

    generate_age_key() is patched to return *fingerprints* in call order
    (each add_host() call inside the `with` block consumes the next one);
    _create_host_secrets_file() (the only sops-shelling step) is a no-op.
    Real sops/age integration is TestAddHostSops's job, not this one's.
    """
    with (
        patch("mac2nix.generators.scaffold.generate_age_key", side_effect=list(fingerprints)),
        patch("mac2nix.generators.scaffold._create_host_secrets_file"),
    ):
        yield


class TestAddHostFiles:
    def test_first_host_creates_files_with_placeholders_substituted(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "repo"
        init_framework(output_dir)

        with _mocked_crypto("age1hosta-fingerprint"):
            fingerprint = add_host(output_dir, "hosta", "alice", confirm_backup=lambda _: True)

        assert fingerprint == "age1hosta-fingerprint"

        config = (output_dir / "hosts" / "darwin" / "hosta" / "configuration.nix").read_text()
        assert "__HOSTNAME__" not in config
        assert "__USERNAME__" not in config
        assert "hosta" in config
        assert "alice" in config

        meta = json.loads((output_dir / "hosts" / "darwin" / "hosta" / ".mac2nix-meta.json").read_text())
        assert meta == {
            "hostname": "hosta",
            "username": "alice",
            "system": "aarch64-darwin",
            "age_public_key": "age1hosta-fingerprint",
        }

        user_config = (output_dir / "users" / "alice.nix").read_text()
        assert "__USERNAME__" not in user_config
        assert "alice" in user_config

    def test_second_host_same_username_leaves_user_file_untouched(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "repo"
        init_framework(output_dir)

        with _mocked_crypto("age1hosta-fingerprint", "age1hostb-fingerprint"):
            add_host(output_dir, "hosta", "shareduser", confirm_backup=lambda _: True)

            user_file = output_dir / "users" / "shareduser.nix"
            before_mtime = user_file.stat().st_mtime_ns
            before_content = user_file.read_text()

            add_host(output_dir, "hostb", "shareduser", confirm_backup=lambda _: True)

        assert user_file.stat().st_mtime_ns == before_mtime
        assert user_file.read_text() == before_content
        assert (output_dir / "hosts" / "darwin" / "hosta").is_dir()
        assert (output_dir / "hosts" / "darwin" / "hostb").is_dir()

    def test_duplicate_hostname_raises_and_writes_nothing(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "repo"
        init_framework(output_dir)

        with _mocked_crypto("age1hosta-fingerprint"):
            add_host(output_dir, "hosta", "alice", confirm_backup=lambda _: True)

        before = sorted(p.relative_to(output_dir) for p in output_dir.rglob("*"))

        with (
            _mocked_crypto("age1hosta-fingerprint-again"),
            pytest.raises(ScaffoldError, match="already registered"),
        ):
            add_host(output_dir, "hosta", "alice", confirm_backup=lambda _: True)

        after = sorted(p.relative_to(output_dir) for p in output_dir.rglob("*"))
        assert before == after

    def test_non_framework_directory_missing_flake_raises(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "not-a-framework"
        output_dir.mkdir()

        with pytest.raises(ScaffoldError, match="not a mac2nix-scaffolded framework"):
            add_host(output_dir, "hosta", "alice", confirm_backup=lambda _: True)

    def test_non_framework_directory_missing_sentinel_raises(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "not-a-framework"
        output_dir.mkdir()
        (output_dir / "flake.nix").write_text("{ }")  # a flake.nix, but not mac2nix's

        with pytest.raises(ScaffoldError, match="not a mac2nix-scaffolded framework"):
            add_host(output_dir, "hosta", "alice", confirm_backup=lambda _: True)

    def test_flake_nix_missing_end_sentinel_raises_clean_error(self, tmp_path: Path) -> None:
        """BEGIN present but END damaged/removed must raise ScaffoldError, not a raw ValueError."""
        output_dir = tmp_path / "repo"
        init_framework(output_dir)

        flake_path = output_dir / "flake.nix"
        flake_path.write_text(flake_path.read_text().replace("# MAC2NIX:HOSTS:END", ""))

        with pytest.raises(ScaffoldError, match="not a mac2nix-scaffolded framework"):
            add_host(output_dir, "hosta", "alice", confirm_backup=lambda _: True)

    def test_confirm_backup_false_leaves_no_host_artifacts(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "repo"
        init_framework(output_dir)

        with _mocked_crypto("age1hosta-fingerprint"), pytest.raises(ScaffoldError, match="not confirmed"):
            add_host(output_dir, "hosta", "alice", confirm_backup=lambda _: False)

        assert not (output_dir / "hosts" / "darwin" / "hosta").exists()
        assert not (output_dir / "users" / "alice.nix").exists()
        assert not (output_dir / "secrets" / "hosta.yaml").exists()

        flake_content = (output_dir / "flake.nix").read_text()
        assert "hosta" not in flake_content
        # The cleanup handler's self-heal always regenerates .sops.yaml (even to an
        # empty creation_rules list) — its presence isn't the point, its content is.
        if (output_dir / ".sops.yaml").is_file():
            assert "hosta" not in (output_dir / ".sops.yaml").read_text()

    def test_late_sops_failure_rolls_back_and_reverts_flake_and_sops(self, tmp_path: Path) -> None:
        """A failure in the sops-shelling step (Step 6) must undo everything Step 4-6 already
        wrote for the failing host — including the flake.nix/.sops.yaml regeneration that
        already happened by that point — while leaving an earlier, successfully-registered
        host completely untouched."""
        output_dir = tmp_path / "repo"
        init_framework(output_dir)

        with (
            patch(
                "mac2nix.generators.scaffold.generate_age_key",
                side_effect=["age1hosta-fingerprint", "age1hostb-fingerprint"],
            ),
            patch(
                "mac2nix.generators.scaffold._create_host_secrets_file",
                side_effect=[None, ScaffoldError("sops failed for testing")],
            ),
        ):
            add_host(output_dir, "hosta", "alice", confirm_backup=lambda _: True)

            with pytest.raises(ScaffoldError, match="sops failed for testing"):
                add_host(output_dir, "hostb", "bob", confirm_backup=lambda _: True)

        assert not (output_dir / "hosts" / "darwin" / "hostb").exists()
        assert not (output_dir / "users" / "bob.nix").exists()
        assert not (output_dir / "secrets" / "hostb.yaml").exists()

        flake_content = (output_dir / "flake.nix").read_text()
        assert "hostb" not in flake_content
        assert "hosta" in flake_content

        sops_config = yaml.safe_load((output_dir / ".sops.yaml").read_text())
        rules = sops_config["creation_rules"]
        assert len(rules) == 1
        assert rules[0]["key_groups"] == [{"age": ["age1hosta-fingerprint"]}]

    def test_second_host_same_username_failure_leaves_shared_user_file_untouched(self, tmp_path: Path) -> None:
        """A second host sharing an existing username must not have its shared
        users/<name>.nix rolled back if that second host's add_host() call fails —
        user_file_created is False for it, since the file predates this call."""
        output_dir = tmp_path / "repo"
        init_framework(output_dir)

        with _mocked_crypto("age1hosta-fingerprint"):
            add_host(output_dir, "hosta", "shareduser", confirm_backup=lambda _: True)

        user_file = output_dir / "users" / "shareduser.nix"
        before_mtime = user_file.stat().st_mtime_ns
        before_content = user_file.read_text()

        with (
            patch("mac2nix.generators.scaffold.generate_age_key", return_value="age1hostb-fingerprint"),
            patch(
                "mac2nix.generators.scaffold._create_host_secrets_file",
                side_effect=ScaffoldError("sops failed for testing"),
            ),
            pytest.raises(ScaffoldError, match="sops failed for testing"),
        ):
            add_host(output_dir, "hostb", "shareduser", confirm_backup=lambda _: True)

        assert not (output_dir / "hosts" / "darwin" / "hostb").exists()
        assert user_file.stat().st_mtime_ns == before_mtime
        assert user_file.read_text() == before_content

    def test_cleanup_time_regeneration_failure_does_not_mask_original_exception(self, tmp_path: Path) -> None:
        """If cleanup's own re-invocation of _regenerate_sops_yaml() fails, the
        ORIGINAL add_host() failure must still propagate — not the cleanup-time one."""
        output_dir = tmp_path / "repo"
        init_framework(output_dir)

        real_regenerate_sops_yaml = scaffold_module._regenerate_sops_yaml
        calls: list[int] = []

        def flaky_regenerate_sops_yaml(output_dir: Path, metas: list[dict]) -> None:
            calls.append(1)
            if len(calls) == 2:
                raise RuntimeError("cleanup-time regen failure")
            real_regenerate_sops_yaml(output_dir, metas)

        with (
            patch("mac2nix.generators.scaffold.generate_age_key", return_value="age1hosta-fingerprint"),
            patch(
                "mac2nix.generators.scaffold._create_host_secrets_file",
                side_effect=ScaffoldError("sops failed for testing"),
            ),
            patch("mac2nix.generators.scaffold._regenerate_sops_yaml", side_effect=flaky_regenerate_sops_yaml),
            pytest.raises(ScaffoldError, match="sops failed for testing"),
        ):
            add_host(output_dir, "hosta", "alice", confirm_backup=lambda _: True)

    def test_age_key_path_inside_output_dir_raises_before_generating_key(self, tmp_path: Path) -> None:
        """Guards against a resolved age-key path landing inside output_dir — a real
        secret-leak risk since the CLI instructs users to push output_dir to a
        (potentially public) git remote."""
        output_dir = tmp_path / "repo"
        init_framework(output_dir)

        with (
            _redirect_age_keys(output_dir),
            patch("mac2nix.generators.scaffold.generate_age_key") as mock_generate,
            pytest.raises(ScaffoldError, match="refusing to generate an age key inside"),
        ):
            add_host(output_dir, "hosta", "alice", confirm_backup=lambda _: True)

        mock_generate.assert_not_called()
        assert not (output_dir / "hosts" / "darwin" / "hosta").exists()
        assert not (output_dir / "users" / "alice.nix").exists()

    def test_missing_state_file_produces_no_warning_and_creates_state_file(
        self, tmp_path: Path, caplog: pytest.LogCaptureFixture
    ) -> None:
        output_dir = tmp_path / "repo"
        init_framework(output_dir)
        assert not (output_dir / ".mac2nix-state.json").exists()

        with (
            _mocked_crypto("age1hosta-fingerprint"),
            caplog.at_level(logging.WARNING, logger="mac2nix.generators.scaffold"),
        ):
            add_host(output_dir, "hosta", "alice", confirm_backup=lambda _: True)

        assert not caplog.records
        stored = json.loads((output_dir / ".mac2nix-state.json").read_text())
        assert "flake_hosts_block_hash" in stored

    def test_hand_edited_flake_hosts_block_triggers_warning_on_next_add_host(
        self, tmp_path: Path, caplog: pytest.LogCaptureFixture
    ) -> None:
        output_dir = tmp_path / "repo"
        init_framework(output_dir)

        with _mocked_crypto("age1hosta-fingerprint"):
            add_host(output_dir, "hosta", "alice", confirm_backup=lambda _: True)

        flake_path = output_dir / "flake.nix"
        flake_path.write_text(flake_path.read_text().replace("hosta", "HOSTA-HAND-EDITED"))

        with (
            _mocked_crypto("age1hostb-fingerprint"),
            caplog.at_level(logging.WARNING, logger="mac2nix.generators.scaffold"),
        ):
            add_host(output_dir, "hostb", "bob", confirm_backup=lambda _: True)

        assert "doesn't match what add-host last wrote" in caplog.text

    def test_corrupt_state_file_handled_gracefully(self, tmp_path: Path, caplog: pytest.LogCaptureFixture) -> None:
        output_dir = tmp_path / "repo"
        init_framework(output_dir)

        with _mocked_crypto("age1hosta-fingerprint"):
            add_host(output_dir, "hosta", "alice", confirm_backup=lambda _: True)

        (output_dir / ".mac2nix-state.json").write_text("{not valid json")

        with (
            _mocked_crypto("age1hostb-fingerprint"),
            caplog.at_level(logging.WARNING, logger="mac2nix.generators.scaffold"),
        ):
            add_host(output_dir, "hostb", "bob", confirm_backup=lambda _: True)

        assert not caplog.records
        stored = json.loads((output_dir / ".mac2nix-state.json").read_text())
        assert "flake_hosts_block_hash" in stored


# ---------------------------------------------------------------------------
# add_host() — real sops/age integration (nix-marked)
# ---------------------------------------------------------------------------


@pytest.fixture
def require_add_host_crypto_deps() -> None:
    if not _has_add_host_crypto_deps():
        pytest.skip("age-keygen and/or sops not on PATH")


@pytest.mark.nix
@pytest.mark.usefixtures("require_add_host_crypto_deps")
class TestAddHostSops:
    def test_host_a_produces_correctly_scoped_sops_and_secrets(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "repo"
        init_framework(output_dir)

        with _redirect_age_keys(tmp_path / "age-keys"):
            fingerprint_a = add_host(output_dir, "hosta", "alice", confirm_backup=lambda _: True)

        sops_config = yaml.safe_load((output_dir / ".sops.yaml").read_text())
        rules = sops_config["creation_rules"]
        assert len(rules) == 1
        assert rules[0]["key_groups"] == [{"age": [fingerprint_a]}]
        assert re.search(rules[0]["path_regex"], "secrets/hosta.yaml")
        assert not re.search(rules[0]["path_regex"], "secrets/hostb.yaml")

        assert (output_dir / "secrets" / "hosta.yaml").is_file()

    def test_host_b_added_without_disturbing_host_a_and_cannot_decrypt_its_secrets(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "repo"
        init_framework(output_dir)
        key_root = tmp_path / "age-keys"

        with _redirect_age_keys(key_root):
            add_host(output_dir, "hosta", "alice", confirm_backup=lambda _: True)

            meta_a_path = output_dir / "hosts" / "darwin" / "hosta" / ".mac2nix-meta.json"
            secrets_a_path = output_dir / "secrets" / "hosta.yaml"
            meta_a_before = meta_a_path.read_text()
            secrets_a_before = secrets_a_path.read_text()

            add_host(output_dir, "hostb", "bob", confirm_backup=lambda _: True)

        # A's own files are untouched by B's registration.
        assert meta_a_path.read_text() == meta_a_before
        assert secrets_a_path.read_text() == secrets_a_before

        sops_config = yaml.safe_load((output_dir / ".sops.yaml").read_text())
        flake_content = (output_dir / "flake.nix").read_text()
        assert len(sops_config["creation_rules"]) == 2
        assert "hosta" in flake_content
        assert "hostb" in flake_content

        # B's key cannot decrypt A's secrets — a real sops --decrypt attempt.
        b_key_path = key_root / "bob" / "keys.txt"
        env = {**os.environ, "SOPS_AGE_KEY_FILE": str(b_key_path)}
        result = subprocess.run(  # noqa: S603
            ["sops", "--decrypt", str(secrets_a_path)],  # noqa: S607
            cwd=output_dir,
            env=env,
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode != 0

    def test_duplicate_key_metadata_triggers_uniqueness_error_and_rolls_back(self, tmp_path: Path) -> None:
        output_dir = tmp_path / "repo"
        init_framework(output_dir)
        key_root = tmp_path / "age-keys"

        with _redirect_age_keys(key_root):
            fingerprint_a = add_host(output_dir, "hosta", "alice", confirm_backup=lambda _: True)

            with (
                patch("mac2nix.generators.scaffold.generate_age_key", return_value=fingerprint_a),
                pytest.raises(ScaffoldError, match="share the same age public key"),
            ):
                add_host(output_dir, "hostc", "carol", confirm_backup=lambda _: True)

        # Rollback: hostc leaves no trace, flake.nix/.sops.yaml revert to hosta only.
        assert not (output_dir / "hosts" / "darwin" / "hostc").exists()
        assert not (output_dir / "users" / "carol.nix").exists()
        assert not (output_dir / "secrets" / "hostc.yaml").exists()

        flake_content = (output_dir / "flake.nix").read_text()
        assert "hostc" not in flake_content
        assert "hosta" in flake_content

        sops_config = yaml.safe_load((output_dir / ".sops.yaml").read_text())
        rules = sops_config["creation_rules"]
        assert len(rules) == 1
        assert rules[0]["key_groups"] == [{"age": [fingerprint_a]}]
