"""mac2nix data models."""

from mac2nix.models.application import (
    ApplicationsResult,
    AppSource,
    BinarySource,
    BrewCask,
    BrewFormula,
    BrewService,
    HomebrewState,
    InstalledApp,
    MasApp,
    PathBinary,
)
from mac2nix.models.files import (
    AppConfigEntry,
    AppConfigResult,
    BundleEntry,
    ConfigFileType,
    DotfileEntry,
    DotfileManager,
    DotfilesResult,
    FontCollection,
    FontEntry,
    FontSource,
    FontsResult,
    KeyBindingEntry,
    LibraryAuditResult,
    LibraryDirEntry,
    LibraryFileEntry,
    WorkflowEntry,
)
from mac2nix.models.hardware import (
    AudioConfig,
    AudioDevice,
    DisplayConfig,
    Monitor,
    NightShiftConfig,
)
from mac2nix.models.preferences import PreferencesDomain, PreferencesResult, PreferenceValue
from mac2nix.models.services import (
    CronEntry,
    LaunchAgentEntry,
    LaunchAgentSource,
    LaunchAgentsResult,
    LaunchdScheduledJob,
    ScheduledTasks,
    ShellConfig,
    ShellFramework,
)
from mac2nix.models.system import (
    FirewallAppRule,
    NetworkConfig,
    NetworkInterface,
    PrinterInfo,
    SecurityState,
    SystemConfig,
    TimeMachineConfig,
    VpnProfile,
)
from mac2nix.models.system_state import SystemState

__all__ = [
    "AppConfigEntry",
    "AppConfigResult",
    "AppSource",
    "ApplicationsResult",
    "AudioConfig",
    "AudioDevice",
    "BinarySource",
    "BrewCask",
    "BrewFormula",
    "BrewService",
    "BundleEntry",
    "ConfigFileType",
    "CronEntry",
    "DisplayConfig",
    "DotfileEntry",
    "DotfileManager",
    "DotfilesResult",
    "FirewallAppRule",
    "FontCollection",
    "FontEntry",
    "FontSource",
    "FontsResult",
    "HomebrewState",
    "InstalledApp",
    "KeyBindingEntry",
    "LaunchAgentEntry",
    "LaunchAgentSource",
    "LaunchAgentsResult",
    "LaunchdScheduledJob",
    "LibraryAuditResult",
    "LibraryDirEntry",
    "LibraryFileEntry",
    "MasApp",
    "Monitor",
    "NetworkConfig",
    "NetworkInterface",
    "NightShiftConfig",
    "PathBinary",
    "PreferenceValue",
    "PreferencesDomain",
    "PreferencesResult",
    "PrinterInfo",
    "ScheduledTasks",
    "SecurityState",
    "ShellConfig",
    "ShellFramework",
    "SystemConfig",
    "SystemState",
    "TimeMachineConfig",
    "VpnProfile",
    "WorkflowEntry",
]
